### PR TITLE
Bigint

### PR DESCRIPTION
**Pull request by markrogoyski**
Added some unit tests for BigInt.

### CODE REVIEW

**Comment by markrogoyski** [comment]
My intention was to add a few unit tests, but GitHub seems to treat my changes as conflicts rather than additions, as it seems to think I am adding the entire file. I did a pull request from your branch into a bigint branch in my repo, made some additions, and then opened this pull request from my branch into yours.

Anyhow, a couple of my unit tests are commented out because they don't seem to work. __toString seems to crash when the number gets large--and it doesn't even need to be bigger than max int size.

Also, I'm not quite sure what the array constructor is doing. I have a simple test that is commented out because it fails. Can you check that out and see if that is supposed to work, or if my understanding of it is just wrong.
Thanks.

**Comment by markrogoyski** [comment]
I think the reason for the strange merge conflict is because I did not fork your repo, and therefore, did not have your history of making the BigInt files to which I am just making a modification of. When I created a local branch, it was off my develop, and I did a pull request from your repo/branch into my branch, and made my additions. Then when I opened the pull request into your repo/branch, from my repo's perspective BigInt was something newly added, so from your repo's perspective, it considers it to be of a different history, and won't merge it automatically, I think.

**Comment by Beakerboy** [comment]
The array constructor is just a way to directly set the value of the two ints in the object. It's probably easiest to think about this class in terms of binary or hex. If you take a signed 128 bit int, and split it into two 64 bit pieces and look at them as 64 bit signed integers, what is their value?

For example, in 4 bit world, a big int would be 8 bits. -1 in 8 bit is 11111111. Or two 4 bit groups of 1111 1111, or [-1, -1]. 8 bit int max is 01111111 and 4 bit int max is 0111. So 8 bit int max is 0111 1111, or [-1, int_max]. Int min is 10000000, or 1000 0000, or [0, int_min].
$value[0] is the rightmost word and it grows to the left. This way as the bit number increases, the word number(index) increases

**Comment by markrogoyski** [comment]
OK. I think the confusing part for me was how a large positive number has a negative 0 element in the array.

Btw, were you able to reproduce the toString issue? It seems to go into an infinite loop. I didn't investigate what it is doing yet, but it seems large numbers (not necessarily bit int sized numbers) get into this loop.

**Comment by Beakerboy** [comment]
I'm closing this, and I suggest you delete your fork. I'm going to use a much better way of handling large numbers. instead of using arrays, I'll pack the large numbers into strings.

**Comment by markrogoyski** [comment]
OK. Thanks for the update.

**Pull request closed without merging**
